### ISSUE TITLE
IllegalArgumentException when registering new AliveServer

### ISSUE THREAD

**Issue by devgianlu** [devgianlu/PretendYoureXyzzy#2]
On the server side:
```
2018-08-20 15:41:20 ERROR request:368 - UT005071: Undertow request failed HttpServerExchange{ POST /AmAlive request {Accept=[text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2], Connection=[keep-alive], Content-type=[application/x-www-form-urlencoded], Content-Length=[276], User-Agent=[Java/1.8.0_102], Host=[localhost]} response {}}
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'name' of com/gianlu/pyxserverdiscoveryapi/ServersList$AliveServer.<init> must not be null
	at com.gianlu.pyxserverdiscoveryapi.ServersList$AliveServer.$$$reportNull$$$0(ServersList.java)
	at com.gianlu.pyxserverdiscoveryapi.ServersList$AliveServer.<init>(ServersList.java)
	at com.gianlu.pyxserverdiscoveryapi.ServersList.create(ServersList.java:27)
	at com.gianlu.pyxserverdiscoveryapi.handlers.AmAliveHandler.handleRequest(AmAliveHandler.java:83)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:332)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
Additional info: https://github.com/devgianlu/PretendYoureXyzzy/pull/1#issuecomment-414311279

**Comment by devgianlu** [comment]
`org.jetbrains:annotations:16.0.1` and newer seems to be bugged for me. Deploying the working server now.

**Comment by twrist** [comment]
Initial registration works, however the follow up keepalive fails with a 400:  
```
{"publicKey":"70fe0d2d0e1610c64ad2b428be35fbd049600e68526d0689bab0cc0d232d37880ad50b624e97c275ea11308e1b63106c10831f7201dee1f74fe9404c81666a81f3da165687d3377a801cded707ddf10435746a1b3cf01845b63f2410afc2737e"}
077.072.083.170.60145-139.099.141.051.00080: +&Cookie: mstshash=hello

139.099.141.051.00080-077.072.083.170.60145: HTTP/1.0 400 Bad request
Cache-Control: no-cache
Connection: close
Content-Type: text/html

<html><body><h1>400 Bad request</h1>
Your browser sent an invalid request.
</body></html>
```
